import assert from 'node:assert/strict';
import { setTimeout } from 'node:timers/promises';
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const dataRevision = '8fe210b21c9abbe73de93670f3d5a346c80a3625';
const artRevision = '2ecb4eeacd5a1718621fc30f12772e3f60d830b9';
const dataUrl = `https://raw.githubusercontent.com/PokeAPI/pokeapi/${dataRevision}/data/v2/csv/pokemon_species.csv`;
const artBase = `https://cdn.jsdelivr.net/gh/PokeAPI/sprites@${artRevision}/sprites/pokemon/other/official-artwork`;
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');
async function download(url) {
  for (let attempt = 0; ; attempt++) {
    try {
      const response = await fetch(url, { signal: AbortSignal.timeout(30000) });
      assert.equal(response.status, 200, url);
      return Buffer.from(await response.arrayBuffer());
    } catch (error) {
      if (attempt === 4) throw error;
      await setTimeout(500 * 2 ** attempt);
    }
  }
}

const csv = await download(dataUrl);
assert.ok(csv.toString().startsWith('id,identifier,'));
// The first two fields are numeric IDs and unquoted ASCII identifiers in this
// pinned PokéAPI CSV. Reject unexpected syntax rather than parsing arbitrary CSV.
const species = csv
  .toString()
  .trim()
  .split('\n')
  .slice(1)
  .map((line) => {
    const [id, name] = line.split(',');
    assert.match(id, /^\d+$/);
    assert.match(name, /^[a-z0-9-]+$/);
    return { id: Number(id), name, imagePath: `/pokemon/${id}.png` };
  })
  .filter(({ id }) => id >= 1 && id <= 151)
  .sort((a, b) => a.id - b.id);
assert.deepEqual(
  species.map(({ id }) => id),
  Array.from({ length: 151 }, (_, i) => i + 1),
);
assert.equal(new Set(species.map(({ name }) => name)).size, 151);
await mkdir('public/pokemon', { recursive: true });
await mkdir('src/shared/catalog', { recursive: true });
let previous;
try {
  previous = JSON.parse(
    await readFile('src/shared/catalog/sources.json', 'utf8'),
  );
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
const images = [];
let cursor = 0;
await Promise.all(
  Array.from({ length: 3 }, async () => {
    while (cursor < species.length) {
      const entry = species[cursor++];
      const path = `public${entry.imagePath}`;
      let bytes;
      const known = previous?.images.find((image) => image.id === entry.id);
      if (previous?.artRevision === artRevision && known) {
        try {
          bytes = await readFile(path);
        } catch (error) {
          if (error.code !== 'ENOENT') throw error;
        }
        if (bytes && digest(bytes) !== known.sha256) bytes = undefined;
      }
      bytes ??= await download(`${artBase}/${entry.id}.png`);
      assert.equal(
        bytes.subarray(0, 8).toString('hex'),
        '89504e470d0a1a0a',
        path,
      );
      assert.equal(bytes.subarray(12, 16).toString(), 'IHDR', path);
      assert.equal(bytes.readUInt32BE(16), 475, path);
      assert.equal(bytes.readUInt32BE(20), 475, path);
      assert.ok(bytes.length < 1024 * 1024, path);
      await writeFile(path, bytes);
      images.push({ id: entry.id, sha256: digest(bytes), bytes: bytes.length });
    }
  }),
);
images.sort((a, b) => a.id - b.id);
const sql =
  '-- PokéAPI catalog snapshot; generated by scripts/import-catalog.mjs.\n' +
  '-- Published migration: do not rewrite to refresh the catalog.\n' +
  'INSERT INTO pokemon_species (id, name, image_path) VALUES\n' +
  species
    .map(({ id, name, imagePath }) => `(${id}, '${name}', '${imagePath}')`)
    .join(',\n') +
  ';\n';
const migration = 'migrations/0002_kanto_catalog.sql';
const existing = await readFile(migration, 'utf8');
assert.ok(
  existing.startsWith('-- Custom SQL migration file') || existing === sql,
  'Never overwrite a published migration; create a new migration for catalog changes.',
);
await writeFile(migration, sql);
await writeFile(
  'src/shared/catalog/species.json',
  JSON.stringify(species, null, 2) + '\n',
);
await writeFile(
  'src/shared/catalog/sources.json',
  JSON.stringify(
    {
      dataRevision,
      dataUrl,
      dataSha256: digest(csv),
      artRevision,
      artBase,
      images,
    },
    null,
    2,
  ) + '\n',
);
console.log(
  `Imported ${species.length} species and ${images.length} images (${images.reduce((sum, image) => sum + image.bytes, 0)} bytes).`,
);
